set_property SRC_FILE_INFO {cfile:/home/tansei/Desktop/hardware_kadai/verilog/uart_loopback_kit/test_uart_loopback_9600/test_uart_loopback_9600.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc rfile:../../../test_uart_loopback_9600.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/tansei/Desktop/hardware_kadai/verilog/uart_loopback_kit/test_uart_loopback_9600/test_uart_loopback_9600.srcs/constrs_1/new/test_uart_loopback.xdc rfile:../../../test_uart_loopback_9600.srcs/constrs_1/new/test_uart_loopback.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports usb_uart_rxd]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports usb_uart_txd]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets usb_uart_rxd_IBUF]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets usb_uart_txd_OBUF]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out1]]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/uart_loopback_0/inst/u2/rxbuf[0]} {design_1_i/uart_loopback_0/inst/u2/rxbuf[1]} {design_1_i/uart_loopback_0/inst/u2/rxbuf[2]} {design_1_i/uart_loopback_0/inst/u2/rxbuf[3]} {design_1_i/uart_loopback_0/inst/u2/rxbuf[4]} {design_1_i/uart_loopback_0/inst/u2/rxbuf[5]} {design_1_i/uart_loopback_0/inst/u2/rxbuf[6]} {design_1_i/uart_loopback_0/inst/u2/rxbuf[7]}]]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/uart_loopback_0/inst/u2/counter_reg[0]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[1]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[2]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[3]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[4]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[5]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[6]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[7]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[8]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[9]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[10]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[11]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[12]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[13]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[14]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[15]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[16]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[17]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[18]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[19]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[20]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[21]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[22]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[23]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[24]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[25]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[26]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[27]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[28]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[29]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[30]} {design_1_i/uart_loopback_0/inst/u2/counter_reg[31]}]]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/uart_loopback_0/inst/u2/rxd]]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/uart_loopback_0/inst/u2/status]]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/uart_loopback_0/inst/u2/next]]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/uart_loopback_0/inst/u2/watch]]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
