# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/tansei/Desktop/hardware_kadai/vivado/Arty_Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_fadd_0_0/design_1_fadd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fadd_0_0 || ORIG_REF_NAME==design_1_fadd_0_0}]

# IP: bd/design_1/ip/design_1_c_shift_ram_0_0/design_1_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_0_0 || ORIG_REF_NAME==design_1_c_shift_ram_0_0}]

# IP: bd/design_1/ip/design_1_c_shift_ram_1_0/design_1_c_shift_ram_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_1_0 || ORIG_REF_NAME==design_1_c_shift_ram_1_0}]

# IP: bd/design_1/ip/design_1_c_shift_ram_2_0/design_1_c_shift_ram_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_2_0 || ORIG_REF_NAME==design_1_c_shift_ram_2_0}]

# IP: bd/design_1/ip/design_1_util_reduced_logic_0_0/design_1_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_0_0 || ORIG_REF_NAME==design_1_util_reduced_logic_0_0}]

# IP: bd/design_1/ip/design_1_util_reduced_logic_1_0/design_1_util_reduced_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_1_0 || ORIG_REF_NAME==design_1_util_reduced_logic_1_0}]

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# XDC: bd/design_1/design_1_ooc.xdc
